id = "wgsl-wesl"
name = "WGSL/WESL"
version = "0.0.1"
schema_version = 1
authors = ["Lucas de Linhares <lucasdelinhares@gmail.com>"]
description = "Supports grammar for WGSL, WESL as well as best-effort support for Bevy (naga_oil) extensions and uses the wgsl-analyzer LSP"
repository = "https://github.com/lucascompython/wgsl-wesl-zed"


[language_servers.wgsl_analyzer]
name = "wgsl_analyzer"
# languages = ["wgsl", "wesl"]
languages = ["WGSL/WESL"]

[grammars.wesl]
repository = "https://github.com/wgsl-tooling-wg/tree-sitter-wesl"
commit = "81384820b582658b21fc59116b0eac0f3843bd39"
