name = "WGSL/WESL"
grammar = "wesl"
path_suffixes = ["wgsl", "wesl"]
line_comments = ["// "]

brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
]
